import {parseWave,digest,referenceCrop,waveBytes} from '../target/core.js';
const $=id=>document.getElementById(id),audio=$('audio'),refAudio=$('reference-audio');
let manifest,current,original,parsed,objectURL,refURL,generation=0,heard=false;
const cache=new Map(),refCache=new Map();
const describe={revision:'New correlated texture synthesis. Same model settings across takes; fresh seed—not a different simulated gesture.',previous:'Earlier pulse/burst source for comparison. This is the recognizable but rejected sound family from the previous iteration.',control:'Diagnostic only: the revised source spectrum with randomized phases. Listen for the change in structure, not a new pitch or action.'};
function status(text){$('status').textContent=text;}
function save(bytes,name,type){const u=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),4000);}
function volume(){const n=Number($('volume').value);$('volume-label').textContent=n+' dB';audio.volume=10**(n/20);refAudio.volume=10**(n/20);}
function draw(){const ctx=$('wave').getContext('2d'),w=$('wave').width,h=$('wave').height;ctx.clearRect(0,0,w,h);if(!parsed)return;const x=parsed.samples[current.near_channel];ctx.strokeStyle='#50785a';ctx.beginPath();for(let i=0;i<w;i++){const a=Math.floor(i*x.length/w),b=Math.floor((i+1)*x.length/w);let lo=0,hi=0;for(let j=a;j<b;j++){lo=Math.min(lo,x[j]);hi=Math.max(hi,x[j]);}ctx.moveTo(i,h/2-hi*h*.75);ctx.lineTo(i,h/2-lo*h*.75);}ctx.stroke();}
function preview(){audio.pause();if(objectURL)URL.revokeObjectURL(objectURL);const bytes=original;objectURL=URL.createObjectURL(new Blob([bytes],{type:'audio/wav'}));audio.src=objectURL;audio.load();volume();heard=false;draw();}
async function select(){
 const ticket=++generation;audio.pause();audio.removeAttribute('src');audio.load();parsed=null;original=null;$('play').disabled=true;$('download').disabled=true;
 current=manifest.samples.find(x=>x.id===$('variant').value);const entry=current;$('sound-name').textContent=current.title;$('description').textContent=current.kind==='revision'?(current.generation.fitting_scope==='reference_excerpt'?'Revised texture fitted to this six-second reference’s acoustic statistics. This is a representation test, not unseen-action prediction. No recorded fragments are replayed.':'Separate range-fitted source. Its fitting excludes the reference excerpt; the excerpt was previously inspected, so this is not a blind validation.'):describe[current.kind];
 $('play').textContent=current.kind==='revision'?'Play revised source':current.kind==='previous'?'Play previous source':'Play spectrum control';
 try{let bytes=cache.get(entry.id);if(!bytes){const r=await fetch('./generated/'+entry.file);if(!r.ok)throw Error('Audio download failed');bytes=new Uint8Array(await r.arrayBuffer());if(ticket!==generation)return;const sha=await digest(bytes);if(ticket!==generation)return;if(sha!==entry.sha256)throw Error('Audio identity check failed');cache.set(entry.id,bytes);}if(ticket!==generation)return;original=bytes;parsed=parseWave(bytes);if(parsed.frames!==current.frames||parsed.sampleRate!==48000)throw Error('Unexpected generated audio shape');preview();$('play').disabled=false;$('download').disabled=false;
 $('levels').textContent=`${(parsed.frames/parsed.sampleRate).toFixed(2)} seconds · 48 kHz stereo · peak ${parsed.peak.toFixed(3)} · one shared playback gain for both ears. Stereo capture is retained; no mono audition mode.`;status('Ready. Stable names—no shuffled A/B identities.');
 }catch(e){if(ticket===generation){status(e.message);console.error(e);}}
}
function side(){const entries=manifest.samples.filter(x=>x.side===$('side').value);$('variant').replaceChildren(...entries.map(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.title;return o;}));select();}
function setReference(){refAudio.pause();refAudio.removeAttribute('src');refAudio.load();if(refURL)URL.revokeObjectURL(refURL);const bytes=refCache.get($('reference').value);$('reference-status').textContent=bytes?'Exact reference crop verified locally; nothing uploaded.':'No matching reference loaded. Your files stay in this browser.';if(!bytes)return;const r=parseWave(bytes);const near=manifest.reference_descriptors.find(r=>r.id===$('reference').value).side_label==='right'?1:0;const rms=r.rms[near];const gain=Math.min(.04/Math.max(rms,1e-12),.6/Math.max(r.peak,1e-12));const channels=r.samples;const preview=waveBytes(channels.map(x=>Float32Array.from(x,v=>v*gain)),r.sampleRate);refURL=URL.createObjectURL(new Blob([preview],{type:'audio/wav'}));refAudio.src=refURL;refAudio.load();volume();}
$('side').addEventListener('change',side);$('variant').addEventListener('change',select);$('mode').addEventListener('change',()=>{if(parsed)preview();setReference();});$('volume').addEventListener('input',volume);
$('play').addEventListener('click',async()=>{try{audio.currentTime=0;refAudio.pause();await audio.play();}catch(e){status('Playback could not start: '+e.message);}});$('stop').addEventListener('click',()=>{audio.pause();refAudio.pause();});
$('download').addEventListener('click',()=>save(original,current.file,'audio/wav'));audio.addEventListener('play',()=>refAudio.pause());refAudio.addEventListener('play',()=>audio.pause());audio.addEventListener('timeupdate',()=>{if(!audio.paused&&audio.currentTime>.2)heard=true;});
$('reference').addEventListener('change',setReference);$('reference-file').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>64*1024*1024)throw Error('Reference exceeds 64 MiB');const b=new Uint8Array(await file.arrayBuffer()),sha=await digest(b),ref=manifest.reference_descriptors.find(x=>x.sha256===sha);if(!ref)throw Error('This is not an exact supplied chapter WAV. No guessed action or channel accepted.');const crop=referenceCrop(parseWave(b),ref);if(await digest(crop.slice(44))!==ref.crop_pcm_f32_sha256)throw Error('Reference crop identity mismatch');refCache.set(ref.id,crop);$('reference').value=ref.id;setReference();}catch(e){$('reference-status').textContent=e.message;}});
$('save-note').addEventListener('click',()=>{const notes=$('notes').value.trim();if(!heard||!notes){$('note-status').textContent='Play the selected sound and enter your own note first.';return;}save(JSON.stringify({schema:'source-listening-note/1',time_utc:new Date().toISOString(),source_id:current.id,source_sha256:current.sha256,presentation:$('mode').value,element_volume:audio.volume,reference_loaded:refCache.has($('reference').value),reference_id:$('reference').value,notes,interpretation:'One user observation, not physical calibration'},null,2),'source-listening-note.json','application/json');$('note-status').textContent='Saved locally. Nothing submitted to a server.';});
try{const r=await fetch('./generated/iteration.json');if(!r.ok)throw Error('Iteration manifest unavailable');manifest=await r.json();if(manifest.schema!=='source-iteration/1'||manifest.reference_audio_public!==false||manifest.physical_model!==false||manifest.target_accepted!==false||manifest.samples.length!==7)throw Error('Unexpected experiment manifest');for(const x of manifest.samples)if(!/^[a-z0-9-]+\.wav$/.test(x.file)||!/^[a-f0-9]{64}$/.test(x.sha256))throw Error('Invalid asset identity');$('reference').replaceChildren(...manifest.reference_descriptors.map(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.title+' · '+x.crop_s.join('–')+' s';return o;}));$('build-id').textContent='Source model: '+manifest.source_hashes['ku100sim/texture_source.py'];side();}catch(e){status(e.message);console.error(e);}
window.addEventListener('pagehide',()=>{audio.pause();refAudio.pause();if(objectURL)URL.revokeObjectURL(objectURL);if(refURL)URL.revokeObjectURL(refURL);});
