import {parseWave,digest} from '../target/core.js';
const $=id=>document.getElementById(id),audio=$('audio'),canvas=$('mesh'),ctx=canvas.getContext('2d');let manifest,row,state,blob,token=0;
const ids=['rub','light','rate-neutral','hold'];
const expectedFile=(id,suffix)=>id+suffix;
async function getVerified(file,hash){if(!/^[a-z0-9-]+\.(wav|trace\.json|scene\.json|report\.json)$/.test(file))throw Error('Unlisted path');const r=await fetch('./generated/'+file);if(!r.ok)throw Error('Missing '+file);const bytes=new Uint8Array(await r.arrayBuffer());if(await digest(bytes)!==hash)throw Error('Asset identity mismatch');return bytes;}
function save(bytes,name,type){const u=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function project(p){const [x,y,z]=p;return [canvas.width*.50+(x*.93+z*.52)*11500/1000,canvas.height*.52+(-y*.98+z*.37-x*.1)*11500/1000];}
function draw(){if(!state){requestAnimationFrame(draw);return;}const t=Math.max(0,audio.currentTime-.25/343-31/48000);let i=Math.min(state.time_s.length-1,Math.max(0,Math.round(t*60)));const p=state.positions_mm[i];ctx.clearRect(0,0,canvas.width,canvas.height);const faces=state.faces.map(f=>({f,z:f.reduce((a,j)=>a+p[j][2],0)/3})).sort((a,b)=>a.z-b.z);
 for(const {f} of faces){ctx.beginPath();f.forEach((j,k)=>{const a=project(p[j]);if(k)ctx.lineTo(...a);else ctx.moveTo(...a);});ctx.closePath();ctx.fillStyle='#9ab997';ctx.fill();ctx.lineWidth=.65;ctx.strokeStyle='#526e55';ctx.stroke();}
 for(let k=0;k<2;k++){const c=p[state.solid_vertices+k];const xy=project(c),r=state.fingertip_radii_mm[k]*11.5;const gradient=ctx.createRadialGradient(xy[0]-r*.3,xy[1]-r*.35,r*.1,...xy,r);gradient.addColorStop(0,'#efccaa');gradient.addColorStop(1,'#c9956b');ctx.globalAlpha=.82;ctx.fillStyle=gradient;ctx.beginPath();ctx.arc(...xy,r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle='#805c40';ctx.lineWidth=1.4;ctx.stroke();ctx.fillStyle='#3c332d';ctx.font='20px system-ui';ctx.fillText(k?'Thumb proxy':'Fingertip proxy',k?xy[0]+r+14:xy[0]-60,k?xy[1]+5:Math.max(24,xy[1]-r-17));}
 ctx.fillStyle='#426045';ctx.font='15px system-ui';ctx.fillText('34 × 8 × 24 mm connected solid · clamped left edge',22,canvas.height-22);
 $('clock').textContent=t.toFixed(2)+' s';$('force').textContent=state.forces_n[i].map(n=>n.toFixed(2)).join(' / ')+' N';$('volume').textContent=state.min_jacobian[i].toFixed(3)+'–'+state.max_jacobian[i].toFixed(3);$('phase').textContent=t<.3?'Approach':t<.7?'Pinch':t<1.1?'Hold':t<2?'Rub':t<2.4?'Hold':t<3.25?'Reverse':t<3.5?'Squeeze':t<3.8?'Hold':t<4.3?'Release':'Recovery';if(row.id==='hold'&&t>=1.1&&t<3.25)$('phase').textContent='Stationary hold';requestAnimationFrame(draw);}
async function select(){const serial=++token;audio.pause();$('play').disabled=true;row=manifest.samples.find(s=>s.id===$('variant').value);$('title').textContent=row.title;$('status').textContent='Checking audio and mechanical state…';const [ab,tb]=await Promise.all([getVerified(row.audio,row.sha256[row.audio]),getVerified(row.trace,row.sha256[row.trace])]);if(serial!==token)return;const a=parseWave(ab);if(a.sampleRate!==48000||a.samples.length!==2)throw Error('Binaural file required');let difference=0;for(let i=0;i<a.frames;i++)difference=Math.max(difference,Math.abs(a.samples[0][i]-a.samples[1][i]));if(difference<1e-9)throw Error('Duplicated mono rejected');state=JSON.parse(new TextDecoder().decode(tb));if(state.schema!=='hand-geometry-trace/1'||!state.positions_mm.length)throw Error('Invalid physical trace');if(blob)URL.revokeObjectURL(blob);blob=URL.createObjectURL(new Blob([ab],{type:'audio/wav'}));audio.src=blob;audio.load();$('play').disabled=$('download').disabled=$('scene').disabled=false;$('status').textContent='Verified binaural audio and actual simulated state.';$('source').textContent='Peak contact force: '+row.forces_n.map(n=>n.toFixed(2)).join(' / ')+' N. One common listening gain; this is not pressure calibration.';$('download').onclick=()=>save(ab,row.audio,'audio/wav');$('scene').onclick=async()=>{try{const b=await getVerified(row.scene,row.sha256[row.scene]);save(b,row.scene,'application/json');}catch(e){$('status').textContent=e.message;}};}
$('volume-control').oninput=()=>{audio.volume=10**(Number($('volume-control').value)/20);$('volume-label').textContent=$('volume-control').value+' dB';};$('volume-control').oninput();$('play').onclick=async()=>{try{audio.currentTime=0;await audio.play();}catch(e){$('status').textContent=e.message;}};$('stop').onclick=()=>{audio.pause();audio.currentTime=0;};$('variant').onchange=()=>select().catch(e=>{$('status').textContent=e.message;console.error(e);});
try{const r=await fetch('./generated/manifest.json');manifest=await r.json();if(!r.ok||manifest.schema!=='hand-contact-auditions/1'||manifest.raw_recordings_included!==false||manifest.binaural_required!==true||manifest.samples.length!==ids.length||new Set(manifest.samples.map(s=>s.id)).size!==ids.length||manifest.samples.some(s=>!ids.includes(s.id)))throw Error('Invalid manifest');for(const s of manifest.samples){for(const [key,ext]of Object.entries({audio:'.wav',scene:'.scene.json',trace:'.trace.json',report:'.report.json'}))if(s[key]!==expectedFile(s.id,ext))throw Error('Invalid manifest path');$('variant').add(new Option(s.title,s.id));}$('variant').disabled=false;$('variant').value='light';await select();requestAnimationFrame(draw);}catch(e){$('status').textContent='Could not load: '+e.message;console.error(e);}
window.addEventListener('pagehide',()=>{audio.pause();if(blob)URL.revokeObjectURL(blob);});
