#!/usr/bin/env node
/** Ordinary HTTP/HTTPS tests: no navigation-policy changes and no human scores. */
import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import http from 'node:http';import {createHash} from 'node:crypto';import {fileURLToPath,pathToFileURL} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),site=path.resolve(process.env.KU100_SITE_DIR||path.join(root,'dist')),out=path.resolve(process.env.KU100_CONTACT_REPORT_DIR||path.join(root,'validation/local/contact-browser'));
const {chromium,request}=await import(pathToFileURL(process.env.KU100_PLAYWRIGHT_MODULE||path.join(root,'web/node_modules/playwright/index.mjs')).href);const sha=x=>createHash('sha256').update(x).digest('hex');let base=process.env.KU100_CONTACT_URL,server,browser,api;const report={schema:'contact-browser/1',passed:false,assets:[],samples:[],checks:[],errors:[],human_listening_assessed:false};await fs.mkdir(out,{recursive:true});
try{
 const hand=JSON.parse(await fs.readFile(path.join(site,'hand/generated/manifest.json'))),fork=JSON.parse(await fs.readFile(path.join(site,'fork-radiation/generated/manifest.json')));
 if(!base){server=http.createServer(async(req,res)=>{try{let rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(!rel.startsWith('/Ku100-Sim/'))throw Error('Subpath required');rel=rel.slice('/Ku100-Sim/'.length);if(rel.endsWith('/'))rel+='index.html';const file=path.resolve(site,rel);if(!file.startsWith(site+path.sep))throw Error('Bad path');const data=await fs.readFile(file);res.writeHead(200,{'Content-Type':{'.html':'text/html','.js':'text/javascript','.json':'application/json','.wav':'audio/wav','.css':'text/css'}[path.extname(file)]||'application/octet-stream'});res.end(data);}catch{res.writeHead(404);res.end('Not found');}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/Ku100-Sim/`;}
 report.url=base;api=await request.newContext({timeout:30000});const names=['hand/index.html','hand/app.js','hand/style.css','hand/generated/manifest.json','hand/generated/refinement.json','fork-radiation/index.html','fork-radiation/app.js','fork-radiation/generated/manifest.json'];for(const r of hand.samples)for(const field of ['audio','scene','trace','report'])names.push('hand/generated/'+r[field]);for(const r of fork.samples)for(const field of ['file','scene','report'])names.push('fork-radiation/generated/'+r[field]);
 for(const name of names){const expected=sha(await fs.readFile(path.join(site,name)));let row;for(let i=0;i<5;i++){const r=await api.get(new URL(name,base).href,{headers:{'Cache-Control':'no-cache'}});row={path:name,status:r.status(),sha256:sha(await r.body()),expected_sha256:expected};if(row.status===200&&row.sha256===expected)break;await new Promise(r=>setTimeout(r,5000));}report.assets.push(row);assert.equal(row.status,200);assert.equal(row.sha256,expected);}
 browser=await chromium.launch({headless:true,args:['--mute-audio'],...(process.env.KU100_BROWSER_EXECUTABLE?{executablePath:process.env.KU100_BROWSER_EXECUTABLE}:{})});report.browser=browser.version();const context=await browser.newContext({viewport:{width:1380,height:1000},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));page.on('request',r=>{if(/^https?:/.test(r.url())&&(new URL(r.url()).origin!==new URL(base).origin||r.method()!=='GET'))report.errors.push('Unexpected request '+r.url());});
 const decode=async audio=>audio.evaluate(async a=>{const b=await(await fetch(a.src)).arrayBuffer(),{parseWave}=await import('../target/core.js'),p=parseWave(new Uint8Array(b)),d=await new OfflineAudioContext(2,1,p.sampleRate).decodeAudioData(b.slice(0));let error=0,diff=0;for(let c=0;c<2;c++)for(let i=0;i<d.length;i++)error=Math.max(error,Math.abs(p.samples[c][i]-d.getChannelData(c)[i]));for(let i=0;i<d.length;i++)diff=Math.max(diff,Math.abs(d.getChannelData(0)[i]-d.getChannelData(1)[i]));return {channels:d.numberOfChannels,frames:d.length,sample_rate:d.sampleRate,error,ear_difference:diff};});
 assert.equal((await page.goto(new URL('hand/',base).href,{waitUntil:'networkidle'})).status(),200);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Verified binaural'));
 for(const row of hand.samples){await page.locator('#variant').selectOption(row.id);await page.waitForFunction(title=>document.querySelector('#title').textContent===title&&document.querySelector('#status').textContent.startsWith('Verified binaural'),row.title);const audio=page.locator('#audio');const d=await decode(audio);assert.equal(d.error,0);assert.equal(d.channels,2);assert.ok(d.ear_difference>1e-8);assert.equal(d.frames,Math.round(row.seconds*48000));await page.locator('#play').click();await page.waitForFunction(()=>document.querySelector('#audio').currentTime>.15&&!document.querySelector('#audio').paused);await audio.evaluate(a=>{a.pause();a.currentTime=1.8;});await page.waitForFunction(()=>{const a=document.querySelector('#audio');return !a.seeking&&Math.abs(a.currentTime-1.8)<.003;});await page.waitForTimeout(100);assert.match(await page.locator('#force').textContent(),/N$/);assert.notEqual(await page.locator('#force').textContent(),'0.00 / 0.00 N');const pending=page.waitForEvent('download');await page.locator('#download').click();const dl=await pending;assert.equal(await dl.failure(),null);assert.equal(sha(await fs.readFile(await dl.path())),row.sha256[row.audio]);const sdp=page.waitForEvent('download');await page.locator('#scene').click();const sd=await sdp;assert.equal(sha(await fs.readFile(await sd.path())),row.sha256[row.scene]);report.samples.push({id:'hand/'+row.id,...d,played:true,seeked:true,download_identity:true,scene_identity:true});}
 // Save a loaded-contact frame, then reset and verify stationary/no-contact start.
 await page.locator('#variant').selectOption('light');await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Verified binaural'));await page.locator('#audio').evaluate(a=>{a.currentTime=1.8;});await page.waitForTimeout(150);
 for(const width of [1380,390]){await page.setViewportSize({width,height:width===390?844:1050});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,width===390?'hand-mobile.png':'hand-desktop.png'),fullPage:true});}
 await page.locator('#stop').click();await page.waitForFunction(()=>document.querySelector('#audio').paused&&document.querySelector('#audio').currentTime===0);report.checks.push('Actual geometry trace, reaction readout, selection, playback, completed seeks and scene/WAV exports');
 assert.equal((await page.goto(new URL('fork-radiation/',base).href,{waitUntil:'networkidle'})).status(),200);await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('All 7'));
 for(const row of fork.samples){const card=page.locator(`[data-id="${row.id}"]`),audio=card.locator('audio');const d=await decode(audio);assert.equal(d.error,0);assert.equal(d.frames,row.frames);assert.equal(d.channels,2);assert.ok(d.ear_difference>1e-9);await card.locator('button').click();await page.waitForFunction(id=>{const a=document.querySelector(`[data-id="${id}"] audio`);return a.currentTime>.15&&!a.paused;},row.id);assert.equal(await page.locator('audio').evaluateAll(xs=>xs.filter(a=>!a.paused).length),1);await audio.evaluate(a=>{a.pause();a.currentTime=7.;});await page.waitForFunction(id=>{const a=document.querySelector(`[data-id="${id}"] audio`);return !a.seeking&&Math.abs(a.currentTime-7)<.003;},row.id);const dp=page.waitForEvent('download');await card.locator('a.download').click();const dl=await dp;assert.equal(await dl.failure(),null);assert.equal(sha(await fs.readFile(await dl.path())),row.sha256);report.samples.push({id:'fork/'+row.id,...d,played:true,seeked:true,download_identity:true});}
 for(const width of [1380,390]){await page.setViewportSize({width,height:width===390?844:1050});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,width===390?'fork-mobile.png':'fork-desktop.png'),fullPage:true});}
 report.checks.push('All seven preferred fork configurations: two-ear decoding, playback, seeking, exclusive playback and exact downloads');report.checks.push('Ordinary project-subpath navigation, both desktop/mobile layouts, no recording upload or uncaught app errors');assert.deepEqual(report.errors,[]);report.passed=true;await context.close();
}catch(e){report.error=String(e.stack||e);process.exitCode=1;console.error(report.error);}
finally{await fs.writeFile(path.join(out,'contact-browser.json'),JSON.stringify(report,null,2)+'\n');if(browser)await browser.close();if(api)await api.dispose();if(server)await new Promise(r=>server.close(r));console.log(JSON.stringify({passed:report.passed,url:base,samples:report.samples.length}));}
