#!/usr/bin/env python3
"""Package the exact native viewer and generated WAVs for server-free review.

Only the already validated site allowlist is read. No user recordings, source
archives, Git metadata or downloaded research trials are embedded.
"""
import argparse
import base64
import hashlib
import json
from pathlib import Path
from build_site import build_site, ROOT

def module_url(text):return 'data:text/javascript;base64,'+base64.b64encode(text.encode()).decode()

def package(out: Path):
    site=ROOT/'dist';build_site(output=site)
    manifest=json.loads((site/'examples/index.json').read_text())
    embedded={'./examples/index.json':(site/'examples/index.json').read_text()}
    out.mkdir(parents=True,exist_ok=False);audio=out/'audio';audio.mkdir()
    rows=[]
    for entry in manifest['examples']:
        text=(site/'examples'/entry['path']).read_text();bundle=json.loads(text)
        embedded['./examples/'+entry['path']]=text
        data=base64.b64decode(bundle['audio']['base64'],validate=True)
        if hashlib.sha256(data).hexdigest()!=bundle['audio']['sha256']:raise ValueError('Audio identity mismatch')
        (audio/(entry['id']+'.wav')).write_bytes(data)
        rows.append({'id':entry['id'],'scene':bundle['scene'],'metrics':bundle['metrics'],'audio_sha256':bundle['audio']['sha256'],'provenance':bundle['provenance']})
    core=module_url((site/'core.js').read_text());view=module_url((site/'view3d.js').read_text())
    app=(site/'app.js').read_text().replace("'./core.js'",repr(core)).replace("'./view3d.js'",repr(view))
    loader="""const embedded=JSON.parse(document.getElementById('embedded-native-examples').textContent);
const originalFetch=globalThis.fetch.bind(globalThis);
globalThis.fetch=(request,options)=>typeof request==='string'&&Object.hasOwn(embedded,request)?Promise.resolve(new Response(embedded[request],{headers:{'Content-Type':'application/json'}})):originalFetch(request,options);
"""
    # Escape markup-significant characters in untrusted scene names and JSON.
    payload=json.dumps(embedded,ensure_ascii=True).replace('<','\\u003c').replace('&','\\u0026')
    html=(site/'index.html').read_text().replace('<link rel="stylesheet" href="./styles.css">','<style>'+(site/'styles.css').read_text()+'</style>')
    html=html.replace('<script type="module" src="./app.js"></script>',
        '<script type="application/json" id="embedded-native-examples">'+payload+'</script>\n<script type="module" src="'+module_url(loader+app)+'"></script>')
    (out/'Ku100-Research-Preview.html').write_text(html)
    (out/'example-evidence.json').write_text(json.dumps(rows,indent=2,allow_nan=False)+'\n')
    (out/'README.txt').write_text('Open Ku100-Research-Preview.html directly in a browser. No server is required.\nThe seven examples are newly generated by the C++ engine, not reference recordings.\nOriginal stereo WAVs are in audio/. Playback uses common attenuation only.\nUnsteady and fine-texture scenes are controlled physical experiments, not certified KU100 or wet-ASMR realism.\nThe exact source and audio hashes are in example-evidence.json.\n')
    from package_target import package as package_target
    package_target(out/'target.html')
    (out/'checksums.json').write_text(json.dumps({str(p.relative_to(out)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(out.rglob('*')) if p.is_file()},indent=2)+'\n')
    return {'out':str(out),'examples':len(rows),'html_bytes':(out/'Ku100-Research-Preview.html').stat().st_size}
if __name__=='__main__':
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--out',type=Path,default=ROOT/'outputs/review');args=ap.parse_args();print(json.dumps(package(args.out)))
