/** Local-only reference review. Generated source bytes and user recordings never mix in synthesis. */
import {parseWave} from './core.js';
const $=id=>document.getElementById(id), audio={reference:$('reference-audio'),candidate:$('candidate-audio')};
let study,summary,candidate,reference=null,fullReference=null,ctx,nodes={},gains={},urls={},candidateRevision=0,referenceRevision=0;
const bytes64=text=>Uint8Array.from(atob(text),c=>c.charCodeAt(0));
const hash=async bytes=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');
function fail(e){$('target-error').hidden=false;$('target-error').textContent=String(e.message||e);}
function text(tag,value,parent,cls){const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;parent.append(e);return e;}
function download(bytes,name,type){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function wav(w,start=0,end=w.frames){const n=end-start,b=new ArrayBuffer(44+8*n),d=new DataView(b);const word=(o,s)=>{for(let i=0;i<s.length;i++)d.setUint8(o+i,s.charCodeAt(i));};word(0,'RIFF');d.setUint32(4,b.byteLength-8,true);word(8,'WAVEfmt ');d.setUint32(16,16,true);d.setUint16(20,3,true);d.setUint16(22,2,true);d.setUint32(24,w.sampleRate,true);d.setUint32(28,w.sampleRate*8,true);d.setUint16(32,8,true);d.setUint16(34,32,true);word(36,'data');d.setUint32(40,n*8,true);for(let i=0;i<n;i++)for(let e=0;e<2;e++)d.setFloat32(44+i*8+e*4,w.samples[e][start+i],true);return new Uint8Array(b);}
function waveform(id,w){const canvas=$(id),g=canvas.getContext('2d'),width=canvas.width=700,h=canvas.height;g.clearRect(0,0,width,h);const peak=Math.max(w.peak,1e-9);for(let e=0;e<2;e++){g.strokeStyle=e?'#b38149':'#366c64';g.lineWidth=1;g.beginPath();for(let px=0;px<width;px++){const a=Math.floor(px*w.frames/width),b=Math.max(a+1,Math.floor((px+1)*w.frames/width));let lo=0,hi=0;for(let i=a;i<b&&i<w.frames;i++){lo=Math.min(lo,w.samples[e][i]);hi=Math.max(hi,w.samples[e][i]);}const mid=h*(e?.75:.25);g.moveTo(px,mid-lo/peak*h*.22);g.lineTo(px,mid-hi/peak*h*.22);}g.stroke();}g.fillStyle='#64746b';g.font='11px system-ui';g.fillText('L / R · common amplitude scale',8,12);}
function configureAudio(which,bytes){$('target-error').hidden=true;audio[which].pause();if(urls[which])URL.revokeObjectURL(urls[which]);urls[which]=URL.createObjectURL(new Blob([bytes],{type:'audio/wav'}));audio[which].src=urls[which];}
async function ensureContext(){if(!ctx){ctx=new AudioContext();for(const [key,el]of Object.entries(audio)){nodes[key]=ctx.createMediaElementSource(el);gains[key]=ctx.createGain();nodes[key].connect(gains[key]).connect(ctx.destination);}}await ctx.resume();updateGains();}
function scalar(w){const rms=Math.sqrt((w.rms[0]**2+w.rms[1]**2)/2);if(!rms||!w.peak)return 0;return $('match-level').checked?Math.min(.03/rms,.6/w.peak,100):1;}
function updateGains(){const vol=Number($('listen-volume').value);let info=[];for(const [k,v]of [['reference',reference],['candidate',candidate]]){const gain=v?scalar(v.wave):0;if(gains[k])gains[k].gain.setValueAtTime(gain*vol,ctx.currentTime);info.push(k+': '+gain.toFixed(3)+'×');}$('gain-report').textContent=info.join(' · ')+' before common listening volume. Matching is peak-capped and may not reach equal RMS for high-crest-factor clips. Exports remain unchanged.';}
for(const [key,el]of Object.entries(audio)){el.addEventListener('play',()=>{audio[key==='reference'?'candidate':'reference'].pause();ensureContext().catch(fail);});}
$('match-level').addEventListener('change',updateGains);$('listen-volume').addEventListener('input',updateGains);
const fmt=(x,unit='')=>Number.isFinite(x)?x.toFixed(2)+unit:'Not assessed';
function metricsTable(){const body=$('comparison-table').querySelector('tbody');body.replaceChildren();const r=reference?.metrics,c=candidate?.metrics;const row=(name,a,b)=>{const tr=text('tr','',body);text('td',name,tr);text('td',a,tr);text('td',b,tr);};
row('Signed left − right level',fmt(r?.left_minus_right_db,' dB'),fmt(c?.left_minus_right_db,' dB'));
row('Detected envelope peaks / second',fmt(r?.events?.peaks_per_s),fmt(c?.events?.peaks_per_s));
row('Relative activity above −30 dB',fmt(100*r?.events?.activity_fraction_relative_minus30db,'%'),fmt(100*c?.events?.activity_fraction_relative_minus30db,'%'));
for(const b of ['20_250_hz','250_500_hz','500_2000_hz','2000_8000_hz','8000_20000_hz']){const val=m=>{const v=m?.audible_band_energy_fractions?.[b];return v?v.map(x=>fmt(100*x,'%')).join(' / '):'No registered excerpt measurement';};row(b.replaceAll('_',' ')+' · L / R power',val(r),val(c));}
}
async function loadCandidate(id){const revision=++candidateRevision;let c=study.cases.find(x=>x.id===id);
if(id==='plate-baseline'){const b=await(await fetch('./examples/wet-stroke-left.ku100.json')).json();c={id,title:'Previous plate fixture / rejected as target',audio:b.audio,metrics:b.metrics,limits:'Engineering baseline only. The user rejected this sound as unlike the requested target.'};}
if(!c)throw Error('Unknown candidate');const bytes=bytes64(c.audio.base64);if(await hash(bytes)!==c.audio.sha256)throw Error('Generated audio hash mismatch');if(revision!==candidateRevision)return;
candidate={...c,bytes,wave:parseWave(bytes)};configureAudio('candidate',bytes);waveform('candidate-wave',candidate.wave);$('candidate-description').textContent=c.limits;$('candidate-info').textContent=c.native?`Opening ${(1000*c.native.opening_s).toFixed(1)} ms · ${c.native.rate/1000} kHz native integration · measured airborne receiver at 25 cm, ${c.native.azimuth_deg}°. Not direct ear contact.`:'Old generic contact fixture; preserved for an explicit comparison.';$('download-candidate').disabled=false;updateGains();metricsTable();drawSource();}
$('candidate-select').addEventListener('change',()=>loadCandidate($('candidate-select').value).catch(fail));$('download-candidate').addEventListener('click',()=>{if(candidate)download(candidate.bytes,candidate.id+'.wav','audio/wav');});
function localMetrics(w){return{left_minus_right_db:w.rms[0]&&w.rms[1]?20*Math.log10(w.rms[0]/w.rms[1]):null};}
async function setReference(bytes,name,originalHash,start,registered){const wave=parseWave(bytes);reference={bytes,wave,name,source_sha256:originalHash,clip_sha256:await hash(bytes),start_s:start,end_s:start+wave.duration,metrics:registered?.metrics||localMetrics(wave)};configureAudio('reference',bytes);waveform('reference-wave',wave);$('reference-status').textContent=name;$('reference-info').textContent=`${start.toFixed(2)}–${(start+wave.duration).toFixed(2)} s · ${wave.sampleRate} Hz · original L/R order preserved. ${registered?'Registered diagnostic excerpt; prior inspection, not held-out.':'Custom local excerpt; only direct level statistics shown.'} No physical action inferred.`;updateGains();metricsTable();}
async function crop(){if(!fullReference)return;const w=fullReference.wave,start=Number($('crop-start').value),len=Number($('crop-length').value);if(!Number.isFinite(start)||!Number.isFinite(len)||start<0||len<.1||len>12||start+len>w.duration)throw Error('Choose a valid 0.1–12 second excerpt within the file.');const first=Math.round(start*w.sampleRate),end=Math.round((start+len)*w.sampleRate);const reg=summary.references.find(r=>r.source_sha256===fullReference.sha&&r.start_frame===first&&r.end_frame===end);await setReference(wav(w,first,end),fullReference.name,fullReference.sha,first/w.sampleRate,reg);}
$('apply-crop').addEventListener('click',()=>crop().catch(fail));
$('target-file').addEventListener('change',async()=>{try{const f=$('target-file').files[0];if(!f)return;if(f.size>64*1024*1024)throw Error('Local reference must be a stereo PCM/Float32 WAV under 64 MiB. Use chapters 03–06 or a shorter excerpt.');$('reference-status').textContent='Reading locally…';const b=new Uint8Array(await f.arrayBuffer()),sha=await hash(b);fullReference={wave:parseWave(b),sha,name:f.name};$('apply-crop').disabled=false;const known=summary.references.find(r=>r.source_sha256===sha);$('crop-start').value=known?known.start_s:0;$('crop-length').value=Math.min(4,fullReference.wave.duration);await crop();}catch(e){fail(e);}});
let privateReferences=[];
$('reference-select').addEventListener('change',async()=>{try{const x=privateReferences.find(r=>r.id===$('reference-select').value);if(!x)return;fullReference=null;$('apply-crop').disabled=true;const reg=summary.references.find(r=>r.id===x.id);if(await hash(bytes64(x.base64))!==x.sha256)throw Error('Private reference hash mismatch');await setReference(bytes64(x.base64),x.name,x.source_sha256,x.start_s,reg);}catch(e){fail(e);}});
function drawSource(){const can=$('source-trace'),g=can.getContext('2d');can.width=900;g.clearRect(0,0,900,can.height);if(!candidate?.trace){$('source-state').textContent='No pressure-release source state for this baseline.';return;}const rows=candidate.trace.rows,cols=candidate.trace.columns,ip=cols.indexOf('pocket_pressure_pa'),ir=cols.indexOf('opening_radius_m'),it=cols.indexOf('time_s');const peak=Math.max(...rows.map(r=>Math.abs(r[ip])),1e-20),rad=Math.max(...rows.map(r=>r[ir]));for(const [index,scale,color]of [[ip,peak,'#366c64'],[ir,rad,'#b38149']]){g.strokeStyle=color;g.beginPath();rows.forEach((r,i)=>{const x=r[it]/candidate.native.duration*900,y=index===ip?75-r[index]/scale*65:145-r[index]/scale*65;i?g.lineTo(x,y):g.moveTo(x,y);});g.stroke();}$('source-state').textContent=`Green: pocket pressure; amber: opening radius. Source time, before ${(candidate.native.source_to_audio_latency_s*1000).toFixed(2)} ms processing/flight latency. Peak pocket pressure ${candidate.native.max_pressure_pa.toFixed(2)} Pa; energy residual ${candidate.native.max_energy_residual_j.toExponential(2)} J. Numerical checks do not validate the source hypothesis.`;}
$('save-review').addEventListener('click',()=>{const result={version:'ku100-listening-review/1',created_utc:new Date().toISOString(),candidate_id:candidate?.id,candidate_audio_sha256:candidate?.audio.sha256,source_sha256:study?.source_sha256,reference:reference?{name:reference.name,source_sha256:reference.source_sha256,clip_sha256:reference.clip_sha256,start_s:reference.start_s,end_s:reference.end_s}:null,shared_stereo_matching:$('match-level').checked,gains:{reference:reference?scalar(reference.wave):null,candidate:candidate?scalar(candidate.wave):null,volume:Number($('listen-volume').value)},ratings:{transient:$('rating-transient').value||null,wet_texture:$('rating-wet').value||null,spatial:$('rating-spatial').value||null},notes:$('review-notes').value,physical_calibration_claim:false};download(JSON.stringify(result,null,2),'ku100-listening-review.json','application/json');});
async function start(){[study,summary]=await Promise.all(['./target-study.json','./target-reference-summary.json'].map(async u=>{const r=await fetch(u);if(!r.ok)throw Error('Could not load '+u);return r.json();}));if(study.version!=='ku100-target-study/1'||study.reference_audio_included!==false||study.physical_target_accepted!==false)throw Error('Unrecognized or mislabeled source study');const sel=$('candidate-select');sel.replaceChildren();for(const c of study.cases){const o=text('option',c.title,sel);o.value=c.id;}text('option','Previous plate fixture / rejected target',sel).value='plate-baseline';await loadCandidate('release-fast-left');
const embedded=document.getElementById('private-reference-excerpts');if(embedded){privateReferences=JSON.parse(embedded.textContent);for(const r of privateReferences)text('option',r.name,$('reference-select')).value=r.id;const first=privateReferences.find(x=>x.id==='chapter-04')||privateReferences[0];if(first){$('reference-select').value=first.id;$('reference-select').dispatchEvent(new Event('change'));}}
const registry=await(await fetch('./triggers.json')).json();for(const item of registry.items){const card=text('article','',$('trigger-items'),'trigger-card '+item.group);text('span',item.status,card,'label');text('h3',item.object,card);text('p',item.action,card);text('p',item.listen_for,card);text('p',item.gap,card,'small');}for(const s of registry.sources){const div=text('div','',$('trigger-sources'),'source');const a=text('a',s.title,div);a.href=s.url;a.target='_blank';a.rel='noopener noreferrer';text('p',s.support,div);}document.documentElement.dataset.targetReady='true';}
start().catch(fail);
